import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Common/Navbar";
import FooterSection from "./_components/Homepage/Footer/FooterSection";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
})

export const metadata: Metadata = {
  title: "DreamJob- Job Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className}  antialiased`}
      >
        <div className="flex flex-col min-h-screen ">
          <Navbar />
          <main className="flex-grow">{children}</main>
          <FooterSection />
        </div>
      </body>
    </html>
  );
}
